services:
  - type: web
    name: submission-evaluator
    env: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /